import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar, StatusBar } from "@/modules/app";
import { ScrollArea } from "@/modules/app/scroll-area/scroll-area";
// In _app.tsx or layout.tsx


const neue = localFont({
  src: [
    {
      path: "../assets/fonts/NeueMontreal-Regular.woff",
      weight: "400",
      style: "normal",
    },

    {
      path: "../assets/fonts/NeueMontreal-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueMontreal-Medium.woff",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-neue",
});
export const metadata: Metadata = {
  title: "Decentra Learn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neue.variable} antialiased`}>
        <div className="flex w-full h-screen overflow-hidden relative gap-10">
          {/* Fixed Sidebar */}
          <div className="sticky top-5 left-5 bottom-0 h-screen shrink-0 mt-6 w-64">
            <Sidebar />
          </div>

          {/* Scrollable Content */}
          <div className="relative w-full min-h-screen pb-16 max-w-[1440px] mx-auto flex-1">
            <StatusBar />
            <ScrollArea.Root>
              <div className="flex-1 overflow-y-auto">{children}</div>
            </ScrollArea.Root>
          </div>
        </div>
      </body>
    </html>
  );
}
