import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar, StatusBar } from "@/modules/app";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Provider } from "@/modules/providers";
import { AuthHandler } from "@/modules/app/provider/auth";
import { ScrollArea } from "@/modules/app/scroll-area";
import { LatestActivity } from "@/modules/home/components/latest-activity";


const neue = localFont({
  src: [
    {
      path: "../assets/fonts/NeueMontreal-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueMontreal-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueMontreal-Medium.woff",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-neue",
});

export const metadata: Metadata = {
  title: "Decentra Learn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neue.variable} antialiased`}>
        <Provider>
          <div className="flex w-full h-screen relative px-6 gap-6">
            {/* Fixed Sidebar */}
            <div className="mt-6 min-w-[15vw] flex-shrink-0">
              <Sidebar />
            </div>

            {/* Content Area with Fixed StatusBar and Scrollable Children */}
            <div className="flex-1 flex flex-col h-screen">
              {/* Fixed StatusBar */}
              <div className="flex-shrink-0">
                <StatusBar />
              </div>

              {/* Scrollable Content */}
              <div className="flex-1 flex overflow-hidden">
                <ScrollArea.Root className="flex-1 pb-16">
                  {children}
                </ScrollArea.Root>
                <div className="flex-shrink-0">
                  <LatestActivity />
                </div>
              </div>
            </div>
          </div>
          <AuthHandler />
        </Provider>
      </body>
    </html>
  );
}
